version: '2'
services:

  metricbeat-config:
    labels:
        io.rancher.container.start_once: true
        io.rancher.container.pull_image: always
    image: adopteunops/metricbeat-config:1.0.0-SNAPSHOT

  metricbeat-monica:
    image: {{docker_elastic_repo}}/beats/metricbeat:{{elasticsearch_version}}
    labels:
        io.rancher.container.pull_image: always
        io.rancher.sidekicks: metricbeat-config
        io.rancher.scheduler.global: "true"
    volumes:
    - /proc:/hostfs/proc:ro
    - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    - /:/hostfs:ro
    external_links:
    - 'demo-todo/todo:demo-todo'
    - 'demo-spring/demo-monica:demo-spring'
    links:
    - logstash-collector
    volumes_from:
    - metricbeat-config
    command:
    - metricbeat
    - -c
    - /usr/share/metricbeat-config/metricbeat.yml
    - -e
    - -system.hostfs=/hostfs

  logstash-collector-config:
    restart: always
    image: simpletechs/rancher_logstash-config:v0.2.0-smpl1
    labels:
      io.rancher.container.hostname_override: container_name
      logspout.exclude: 'true'
    environment:
      LOGSPOUT: ignore

  logstash-collector:
    restart: always
    tty: true
    volumes_from:
    - logstash-collector-config
    command:
    - logstash
    - -f
    - /etc/logstash
    image: {{docker_elastic_repo}}/logstash/logstash:{{elasticsearch_version}}
    environment:
      xpack.monitoring.enabled: false
      LOGSPOUT: ignore
    stdin_open: true
    volumes:
    - '/var/log:/host/var/log:ro'
    user: root
    labels:
      io.rancher.sidekicks: logstash-collector-config
      io.rancher.scheduler.global: 'true'
      io.rancher.container.hostname_override: container_name
      logspout.exclude: 'true'